- package-lock.json
- package.json
- src/AdminDashboard.jsx
- src/App.js
- src/Bookings.jsx
- src/Dashboard.jsx
- src/ForgotPassword.jsx
- src/Location.jsx
- src/LoginDashboard.jsx
- src/Registration.jsx
- src/ResetPassword.jsx
- src/components/Driver.jsx
- src/components/User.jsx
- src/context/ThemeContext.jsx
- src/login.jsx
This PR introduces a global theme toggle feature using ThemeContext.
✅ Features:
- Added a toggle button to switch between dark and light modes
- Applied consistent theming across all major UI pages
- Used React Context API for managing global theme state
- Persisted theme choice using localStorage
🎥 Video Walkthrough:
https://github.com/user-attachments/assets/f684a05d-88ee-4e11-9823-6242c0dd4205
Please review and let me know if any additional pages or components need to be updated for full theme compatibility.
> feat(theme): add global dark/light mode toggle across all UI pages

- package-lock.json
- src/App.js
- src/login.jsx
This pull request improves the login experience by adding clear and visually styled toast notifications using react-toastify. Users now get immediate feedback on successful login (🎉 Welcome back!) and failed attempts (⚠️ Invalid credentials), with proper positioning and auto-dismiss behavior. This resolves Issue #40.
> Toast notification login v2(Enhance Login Feedback with Toast Notifications (Fixes #40))

- server/Controllers/BookingControllers/acceptBookingController.js
- server/Controllers/BookingControllers/createBookingController.js
- server/Controllers/BookingControllers/deleteBookingController.js
- server/Controllers/BookingControllers/getAllBookingsController.js
- server/Controllers/BookingControllers/getBookingByPhController.js
- server/Controllers/BookingControllers/sendBookingSMSController.js
- server/Controllers/BookingControllers/updateBookingController.js
- server/Controllers/UserControllers/userLoginController.js
- server/Controllers/UserControllers/userRegisterController.js
- server/Controllers/index.controllers.js
- server/Databases/ConnectDB.js
- server/Models/Booking/Booking.schema.js
- server/Models/User/User.schema.js
- server/Models/index.models.js
- server/configs/Configs.js
- server/package-lock.json
- server/package.json
- server/server.js
Refactored the Express.js backend to a modular and scalable structure to improve maintainability and debugging.
- Separated server and config files
- Restructured routes and middleware
- Improved `.env` handling
- Added logs for DB and server startup
- Fixed Twilio integration error (missing/invalid `TWILIO_ACCOUNT_SID`)
Closes #4
> refactor: modularize Express.js server structure (Closes #4)

- src/Dashboard.jsx
Improved the hovering effects for the Register and Login buttons on the dashboard.
Issue No. #44
> added better hovering effects to login and register buttons

- src/LoginDashboard.jsx
Hello @sailaja-adapa,
Fixed the issue #41
The buttons are redirecting to respected pages upon clicking.
> Fixed Navigation routing issue in LoginDashboard --issue #41

- src/Bookings.jsx
This PR enhances the UI by implementing theme support with smooth and visually appealing light/dark mode transitions across the app.
✅ Key Features:
Updated background gradients and colors using Tailwind CSS for both themes
Improved user experience by blending color palettes and ensuring readability in both modes
📂 Files Modified:
Various JSX components where background and text colors depend on isDarkMode state
CSS classes for gradient and color utilities
📌Visual Improvements:
Dark mode features rich, deep gradients using Tailwind’s gray, blue, and purple shades
> Improved UI of Bookings Page #5

- src/LoginDashboard.jsx
> login dashboard changed

- src/Contact.jsx
- src/Dashboard.jsx
> issue #62 and #63 resolved

- server/.example.env
- server/Controllers/UserControllers/userRegisterController.js
- server/Templates/User/signupMailTemplate.js
- server/Templates/index.templates.js
- server/Utils/sendMail.js
- server/configs/Configs.js
- server/package-lock.json
- server/package.json
This PR introduces a new feature that sends a welcome email to users immediately after successful signup.
- Integrated email sending logic using NodeMailer (or preferred service).
- Triggered email dispatch post successful signup.
- Created a reusable utility for email templates (Welcome).
- Updated `.env.example` to include required email configuration variables.
Closes #56
> [Feature] Send Welcome Email to New Users Upon Signup

- server/Controllers/UserControllers/userLoginController.js
- src/Bookings.jsx
- src/LoginDashboard.jsx
- src/login.jsx
Added user logout with fetching profile
Fix #23
> added-user-logout

- src/About.jsx
- src/AdminDashboard.jsx
- src/Bookings.jsx
- src/Contact.jsx
- src/Dashboard.jsx
- src/ForgotPassword.jsx
- src/Howitworks.jsx
- src/Location.jsx
- src/LoginDashboard.jsx
- src/Registration.jsx
- src/components/Driver.jsx
- src/components/Navbar.css
- src/components/Navbar.jsx
- src/components/User.jsx
- src/login.jsx
This PR improves the website’s responsiveness by implementing a hamburger menu. On smaller screens, the traditional navbar is replaced with a hamburger icon that toggles a side drawer containing the navigation links. Enhances mobile usability and layout consistency.
> Add Responsive Navbar with Hamburger Menu for Mobile View

- package-lock.json
- src/ForgotPassword.jsx
I have fixed the alignment of the forgot password form container and its not colliding with the navbar anymore.
Fixes #132
> Fixed alignment of forgot password form

- server/server.js
- src/App.js
- src/NotFound.jsx
This PR is raised to resolve the issue regarding the Invalid routes that are served by the client side.
> Fix: Invalid URL error handling 

- package-lock.json
- package.json
- src/components/Navbar.jsx
Added The requested icon components also improved visibility
> Fixed Issue with Navbar

- src/Registration.jsx
> FIX #145: dark mode fixed in registration page

- OTP_IMPLEMENTATION_GUIDE.md
- package-lock.json
- server/Controllers/OTPControllers/sendOTPController.js
- server/Controllers/OTPControllers/verifyOTPController.js
- server/Controllers/UserControllers/userRegisterController.js
- server/Controllers/index.controllers.js
- server/Models/OTP/OTP.schema.js
- server/Models/index.models.js
- server/middleware/rateLimiter.js
- server/package-lock.json
- server/package.json
- server/server.js
- server/services/twilioService.js
- src/Registration.jsx
- src/components/OTPVerification.jsx
closes issue #15 
-Added OTP-based mobile number verification to the registration process.
-Integrated Twilio for SMS delivery
-Implemented backend routes: /send-otp, /verify-otp, and updated /register
-Added rate limiting, OTP expiry (10 mins), and failed attempt tracking
-Extended frontend flow to include OTPVerification.jsx for OTP input and validation
-Secured user registration by requiring verified phone numbers before account creation
> otp authentication on registration

- .vscode/settings.json
- package-lock.json
- package.json
- src/NotFound.jsx
Implemented an interactive 404 error page game called "Lost Freight" for the Vipreshana logistics platform. The game transforms a standard error page into an engaging brand experience where users guide a delivery truck through various logistics routes.
- **Grid-based navigation system** with 4 progressive difficulty levels
- **Arrow key controls** with mobile touch/swipe support
- **Click-to-move functionality** for enhanced accessibility
- **Time-based challenges** with level-specific time limits
- **Scoring system** with efficiency bonuses and streak multipliers
- **Collectible coins** (10 points each) with streak mechanics
- **Power-ups** providing score bonuses and time extensions
- **Moving obstacles** that create dynamic challenges
- **Static blocked paths** requiring strategic …
> 404 implementation completed [#191 Resolved]

- README.md
- #193 
- Added Table of Contents with Toggle Button.
- Added LICENSE at last of README.
- 
- 
- @sailaja-adapa
> Added Table of Contents and LICENSE

- package-lock.json
- src/LoginDashboard.jsx
- src/index.js
The text is now better visible and the UI now aligns more with the theme of the website.
> Issue #171 (Text is not properly visible )  resolved

- .github/workflows/issue-welcome.yml
---
Fixes #208   
---
---
Briefly describe what you changed and why:
---
Include any relevant screenshots or demo gifs:
---
---
---
---
and 
> Added the Github Action message

- .github/workflows/issue-welcome.yml
---
Fixes #[issue-number]  
(If no issue is linked, please describe the motivation for this PR.)
---
---
Briefly describe what you changed and why:
---
Include any relevant screenshots or demo gifs:
---
---
---
---
and 
> Added the markdown github action file

- src/login.jsx
---
Fixes #222 
(If no issue is linked, please describe the motivation for this PR.)
---
---
Add live background
Enhanced Sign In page
---
https://github.com/user-attachments/assets/a8bfb141-e474-4e39-9b0f-37acd7469673
---
---
---
---
and 
> Enhance Sign In page

- .vscode/c_cpp_properties.json
- .vscode/launch.json
- .vscode/settings.json
- src/Howitworks.jsx
---
Fixes #244 
---
---
This PR adds a small contact form at the end of howitworks page for users to ask their custom questions freely.
---
---
---
---
---
and 
> added a still questions section at end of howitworks page

- server/Controllers/BookingControllers/createBookingController.js
- server/Controllers/BookingControllers/getBookingByPhController.js
- server/package-lock.json
- server/server.js
Fixes an issue where users couldn't view their bookings using their phone number, even though the bookings were successfully created.
---
---
The application lacked an endpoint to retrieve bookings by phone number, preventing users from accessing their own bookings. This update adds a new route and controller to support that functionality.
- Added `GET /api/bookings/:phone` route in `server.js`  
- Implemented `getBookingByPhController.js` to handle phone-based booking retrieval  
- Included error handling and logging to improve reliability  
---
N/A
---
---
---
> Fix: Add missing phone-based booking retrieval functionality

- src/LoginDashboard.jsx
- src/components/Navbar.jsx
---
Fixes #255   
---
---
This PR fixes the collision of navbar and the user profile icon in the website's dashboard page. Now the icon is visible.
---
Before:
After:
---
---
---
---
and 
> fixed collison of navbar and user logo icon

- server/Controllers/BookingControllers/getBookingByPhController.js
- server/Controllers/OTPControllers/sendOTPController.js
- server/Controllers/OTPControllers/verifyOTPController.js
- server/Controllers/UserControllers/userForgotPasswordController.js
- server/Controllers/UserControllers/userRegisterController.js
- server/Controllers/UserControllers/userResetPasswordController.js
- server/Controllers/index.controllers.js
- server/Models/OTP/OTP.schema.js
- server/middleware/rateLimiter.js
- server/server.js
- server/services/emailOTPService.js
- src/Bookings.jsx
- src/ForgotPassword.jsx
- src/Registration.jsx
- src/ResetPassword.jsx
- src/components/Driver.jsx
- src/components/OTPVerification.jsx
- src/components/User.jsx
- src/config/api.js
- src/login.jsx
✅ Summary
Added email OTP verification alongside SMS OTP
Introduced dual OTP system for registration (email and phone)
Updated login to support both email and phone credentials
Added email input field in the registration form
Enhanced OTP verification flow to handle both types
🚀 Pull Request
Thank you for your contribution! Please fill in the following details to help reviewers evaluate this PR effectively.
📌 Related Issue
Fixes #252 
🔧 Type of Change
Select the relevant option(s):
[x] Bug fix
[ ] New feature
[ ] Documentation update
[ ] Refactoring
[ ] Performance improvement
[ ] UI/UX enhancement
[ ] Other: please specify
📋 Summary of Changes
A brief summary of your changes and the reason behind them:
Enabled email-based OTP flow alongside phone-based OTP
Modified backend controllers …
> feat: Dual OTP Support: Email + Phone

- PASSWORD_STRENGTH_FEATURE.md
- server/Controllers/UserControllers/userRegisterController.js
- server/Controllers/UserControllers/userResetPasswordController.js
- src/Registration.jsx
- src/ResetPassword.jsx
- src/components/PasswordStrengthIndicator.jsx
- src/utils/passwordStrength.js
- src/utils/passwordStrength.test.js
Fixes #[issue-number]  
#256 - Password validation too weak - allows single letter passwords
---
---
Implemented comprehensive password strength validation with real time feedback to address weak password security issues
#Key Changes:
Password Requirements Enforcement:
Minimum 8 characters
At least one uppercase letter
At least one lowercase letter 
At least one number
At least one special character 
Real-time Visual Feedback:
Color coded strength indicator 
Checklist showing which requirements are met
Helpful messages guiding users
Frontend prevents form submission with weak passwords
Backend validates before user registration/password reset
Consistent validation across all password inputs
---
---
---
---
---
> feat: Improving password strength with real time feedback

- src/Location.jsx
---
Fixes #263 
- [ ✅] Bug fix  
- [✅ ] Documentation update  
- [ ✅] UI/UX enhancement  
---
Briefly describe what you changed and why:
In location.jsx previously it has extra toggle button appearing which degrades the Ui so i removed the code of this toggle button because navbar has already dark mode button
---\
after changing ->
---
- [✅ ] My code follows the style guidelines of this project  
- [✅ ] I have performed a self-review of my code  
- [✅ ] I have commented my code where necessary  
- [✅ ] I have made corresponding changes to the documentation  
- [ ✅] I want to work on this further (optional)
---
- [ ✅] I am a SSOC'25 contributor  
- [✅] This PR is part …
> FIX #263: Remove the extra toggle button on navbar
